--- 
index_filenames: 
- index.html
data_sources: 
- items_root: /
  config: 
    allow_periods_in_identifiers: true
  layouts_root: /
  type: filesystem_unified
output_dir: ../Le-Torte-di-Chiara-output-ghpages
site_root: /Le-Torte-di-Chiara/
text_extensions: 
- css
- erb
- haml
- htm
- html
- js
- less
- markdown
- md
- php
- rb
- sass
- scss
- txt
- xhtml
- xml
- textile
enable_output_diff: false
