--- 
output_dir: output-ghpages
text_extensions: 
- css
- erb
- haml
- htm
- html
- js
- less
- markdown
- md
- php
- rb
- sass
- scss
- txt
- xhtml
- xml
- textile
data_sources: 
- items_root: /
  config: 
    allow_periods_in_identifiers: true
  layouts_root: /
  type: filesystem_unified
enable_output_diff: false
site_root: /Le-Torte-di-Chiara/
index_filenames: 
- index.html
